In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# import matplotlib.pyplot as plt

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))
# data = pd.read_csv('/kaggle/input/cifar-10/train.7z')


# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

shutil.unpack_archive('/kaggle/input/cifar-10/train.7z', '/kaggle/working')

In [2]:
from py7zr import unpack_7zarchive
import shutil
import os
# shutil.register_unpack_format('7zip', ['.7z'], unpack_7zarchive)

In [3]:
# train_dir = os.getcwd()+"\\train"
# # test_dir = os.listdir("./test")
# train_dir_len = len(train_dir)
# test_dir_len = len(train_dir)
# print(".\\train:\t",train_dir_len)
# print("files:\t\t",train_dir[:3])
# # print("files:\t\t",test_dir[:3])

In [4]:
train_dir="d:\\P Club task\\train\\train"
# test_dir ="d:\\P Club task\\test\\test"

In [5]:
train_data=[]
test_data = []

In [6]:
import cv2

In [7]:
def load_train(train_data,train_dir):
    os.chdir(train_dir)
    for filename in os.listdir(train_dir):
        img=cv2.imread(os.path.join(os.getcwd(), filename),cv2.IMREAD_GRAYSCALE)
        train_data.append(img)
    return train_data

In [8]:
load_train(train_data,train_dir)

[array([[ 61,  44,  48, ..., 137, 130, 128],
        [ 18,   0,  10, ...,  94,  89,  94],
        [ 23,   8,  31, ...,  90,  90,  80],
        ...,
        [172, 153, 156, ..., 133,  35,  38],
        [146, 128, 143, ..., 152,  69,  59],
        [150, 136, 146, ..., 188, 123,  98]], dtype=uint8),
 array([[123, 102,  92, ..., 206, 204, 206],
        [144, 144, 172, ..., 199, 203, 209],
        [183, 145, 156, ..., 114, 131, 150],
        ...,
        [ 83,  81,  82, ..., 105, 105, 104],
        [ 83,  85,  89, ..., 116, 116, 115],
        [ 84,  88,  95, ..., 120, 120, 120]], dtype=uint8),
 array([[ 61,  47,  41, ..., 158, 171, 129],
        [ 61,  50,  47, ..., 154, 161, 137],
        [ 57,  62,  56, ..., 143, 142, 118],
        ...,
        [141, 116,  76, ...,  78, 115, 112],
        [153, 124,  66, ...,  73, 120, 128],
        [181, 157, 115, ...,  54, 121, 160]], dtype=uint8),
 array([[205, 201, 208, ..., 191, 191, 191],
        [192, 190, 202, ..., 186, 187, 190],
        [192, 19

In [9]:
train_data[0].shape

(32, 32)

In [ ]:
test_dir = "d:\\P Club task\\test\\test"
load_train(test_data,test_dir)

In [ ]:
train_labels = pd.read_csv('d:\\P Club task\\trainLabels.csv',dtype=str)
# train_images = pd.DataFrame(columns = ['id','label','path'],dtype=str)
# test_labels = pd.read_csv('/kaggle/input/cifar-10/sampleSubmission.csv')
# train_labels.info()

In [ ]:
train_labels

In [ ]:
# df = train_images.iloc[1,2]
# df

In [ ]:
image=train_data[0]

In [ ]:
image

In [ ]:
# import Pillow as PIL
# from PIL import Image
from numpy import asarray
# img_gay = Image.open(train_images.iloc[1,2])
# image = img_gay.convert('L')

numpydata = asarray(image) 
numpydat = numpydata.reshape((1024))
numpydat

In [ ]:
class_names = ['airplane','automobile','bird','cat','deer','dog','frog','horse','ship','truck']
for name in  class_names:
    index = class_names.index(name)
    train_labels.loc[train_labels.label==name,'label'] = str(index)
        
display_groupby = train_labels.groupby(['label']).count()
display_groupby.head(10)

In [ ]:
train_labels

In [ ]:
# train_images

In [ ]:
# df = pd.DataFrame(train_images)
# df['path']

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)
one_hot_encoded = encoder.fit_transform(train_labels[['label']])
print(one_hot_encoded.shape)
# def Hot(label) :
#     one_hot_encoded = encoder.fit_transform(label)
#     return one_hot_encoded


In [ ]:
one_hot_encoded[0]

In [ ]:
# df = pd.DataFrame({'Image_Path': ['path/to/image1.jpg', 'path/to/image2.jpg', 'path/to/image3.jpg']})
# df = pd.DataFrame(train_images['path'])

def get_pixel_values(train_data):
#     img = cv2.imread(image_path)  # Read the image
#     img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Convert BGR to RGB
#     img = cv2.resize(img, (32, 32))  # Resize the image to 32x32
#     img = Image.open(image_path)
#     image = img.convert('L')
    train_images=[]
    for i in range(len(train_data)):
        image=train_data[i]
        numpydata = asarray(image)
        numpydat = numpydata.reshape((1024))
        train_images.append(numpydat/255)
#     pixel_values = img.flatten()  # Flatten the image array
    return train_images
# pixel_columns = [f'Pixel_{i}' for i in range(32)]
# df[pixel_columns] = pd.DataFrame(df['path'].apply(get_pixel_values).tolist())
# print(get_pixel_values(train_images.iloc[1,2]))

In [ ]:
train_images=get_pixel_values(train_data)
test_images = get_pixel_values(test_data)

In [ ]:
train_images[0]

In [ ]:
test_images

In [ ]:
tf = pd.DataFrame(train_images)
tf= tf.T
print(tf)

In [ ]:
df = pd.DataFrame(train_images)
df= df.T
print(df)

In [ ]:
train_labels

In [ ]:
training_data=[]

In [ ]:
train_labels['label']=train_labels['label'].astype(int)
train_labels

In [ ]:
train_labels_new=train_labels['label']
train_labels_new

In [ ]:
for i in range(len(train_images)):
    image=train_images[i]
    y=one_hot_encoded[i]
    
    
    training_data.append((image,y))
    

In [ ]:
training_data[0]

In [ ]:
import random
import math

In [ ]:
class ANN:
    def __init__(self, input_size,output_size,learning_rate,num_layers,num_of_nodes_layers):
            self.input_size = input_size
            self.output_size = output_size
            self.learning_rate = learning_rate
            self.num_layers = num_layers
            self.num_of_nodes_layers = num_of_nodes_layers
            self.weights_biases = {}
            self.activations = {}
            

    def initial_params(self):
            np.random.seed(20)
            self.weights_biases['W1'] = np.random.rand(self.num_of_nodes_layers, self.input_size)-0.5
            self.weights_biases['b1'] = np.random.rand(self.num_of_nodes_layers, 1)-0.5

            for i in range(2, self.num_layers + 1):
              self.weights_biases[f'W{i}']= np.random.rand(self.num_of_nodes_layers,self.num_of_nodes_layers)-0.5
              self.weights_biases[f'b{i}']= np.random.rand(self.num_of_nodes_layers, 1)-0.5

            self.weights_biases[f'W{self.num_layers + 1}']= np.random.rand(self.output_size, self.num_of_nodes_layers)-0.5
            self.weights_biases[f'b{self.num_layers + 1}']= np.random.rand(self.output_size, 1)-0.5
    def update_params(self, gradients, momentum_rate):
    for i in range(1, self.num_layers + 2):
        if f"VdW{i}" not in self.weights_biases:
            self.weights_biases[f"VdW{i}"] = np.zeros_like(self.weights_biases[f"W{i}"])
        if f"Vdb{i}" not in self.weights_biases:
            self.weights_biases[f"Vdb{i}"] = np.zeros_like(self.weights_biases[f"b{i}"])
        self.weights_biases[f"VdW{i}"] = (momentum_rate * self.weights_biases[f"VdW{i}"]) + (1 - momentum_rate) * gradients[f"dW{i}"]
        self.weights_biases[f"Vdb{i}"] = (momentum_rate * self.weights_biases[f"Vdb{i}"]) + (1 - momentum_rate) * gradients[f"db{i}"]
        self.weights_biases[f"W{i}"] -= self.learning_rate * self.weights_biases[f"VdW{i}"]
        self.weights_biases[f"b{i}"] -= self.learning_rate * self.weights_biases[f"Vdb{i}"]


    def RELU(self,Z):

            return np.maximum(0,Z)



    def softmax(self,Z):
            Z_max = np.max(Z, axis=0, keepdims=True)
            Z_adjusted = Z - Z_max
            A = np.exp(Z_adjusted) / np.sum(np.exp(Z_adjusted), axis=0)
            return A

    def forward_propagation(self, X):

            self.activations[f'A{0}'] = X

            for i in range(1,self.num_layers + 1):

              W = self.weights_biases[f'W{i}']
              b = self.weights_biases[f'b{i}']
              Z = np.dot(W, self.activations[f'A{i-1}']) + b
              A = self.RELU(Z)
              self.activations[f'A{i}'] = A
              self.activations[f'Z{i}'] = Z

            W = self.weights_biases[f'W{self.num_layers + 1}']
            b = self.weights_biases[f'b{self.num_layers + 1}']
            Z = np.dot(W, self.activations[f'A{self.num_layers }']) + b
            A = self.softmax(Z)
            self.activations[f'A{self.num_layers + 1}'] = A
            self.activations[f'Z{self.num_layers + 1}'] = Z

            cache = {
                'Z': self.activations[f'Z{self.num_layers + 1}'],
                'A': self.activations[f'A{self.num_layers + 1}']
            }


            return A,cache

    def one_hot_encode(self, y):
            num_classes = np.max(y) + 1
            encoded = np.zeros((num_classes, y.shape[0]))
            encoded[y, np.arange(y.shape[0])] = 1
            return encoded

    def total_loss(self,y_pred,Y):

            m = Y.shape[1]
            epsilon = 1e-8

            loss = -np.sum(Y * np.log(y_pred +epsilon)) / m
            return loss

    def backward_prop(self,y_pred,Y):
            m = Y.shape[1]
            dZ_out = y_pred - Y
            gradients = {}
            gradients[f"dW{self.num_layers + 1}"] = (1 / m) * np.dot(dZ_out, self.activations[f"A{self.num_layers}"].T)
            gradients[f"db{self.num_layers + 1}"] = (1 / m) * np.sum(dZ_out, axis=1, keepdims=True)
            dA_prev = np.dot(self.weights_biases[f"W{self.num_layers + 1}"].T, dZ_out)
            for i in range(self.num_layers, 0, -1):
              dZ = np.array(dA_prev, copy=True)
              dZ[self.activations[f"Z{i}"] <= 0] = 0
              gradients[f"dW{i}"] = (1 / m) * np.dot(dZ, self.activations[f"A{i - 1}"].T)
              gradients[f"db{i}"] = (1 / m) * np.sum(dZ, axis=1, keepdims=True)
              dA_prev = np.dot(self.weights_biases[f"W{i}"].T, dZ)

            return gradients



    def update_params(self,gradients):

             for i in range(1, self.num_layers + 2):
              self.weights_biases[f"W{i}"] -= self.learning_rate * gradients[f"dW{i}"]
              self.weights_biases[f"b{i}"] -= self.learning_rate * gradients[f"db{i}"]

    def train(self, X, y, num_iterations, momentum_rate, anneal_rate=None, anneal=True):
            self.initial_params()
            y_encoded = self.one_hot_encode(y)
            prev_loss = float('inf')
            for i in range(num_iterations):
                A, cache = self.forward_propagation(X)
                loss = self.total_loss(A, y_encoded)
                grads = self.backward_prop(A, y_encoded)
                self.update_params(grads, momentum_rate)

                if anneal and loss < prev_loss:
                    self.learning_rate *= 0.5
                    prev_loss = loss
                    continue

                if anneal_rate is not None:
                    self.learning_rate *= anneal_rate

                if (i + 1) % 100 == 0:
                    print(f"Iteration: {i+1}, Loss: {loss:.4f}")



    def predict(self, X):
                b = {}

                A,b = self.forward_propagation(X)
                predictions = np.argmax(A, axis=0)


                return predictions

In [ ]:
model = ANN(input_size=1024, output_size=10, learning_rate=0.1, num_layers=40, num_of_nodes_layers=128,)
model.train(df,train_labels_new, num_iterations=300,momentum_rate=0.8, anneal_rate=0.95, anneal=True)
# Create an instance of the ANN class
ann = ANN(input_size, output_size, learning_rate, num_layers, num_of_nodes_layers)

# Train the model with annealing
ann.train(X_train, y_train, num_iterations, momentum_rate, anneal_rate=0.95, anneal=True)


In [ ]:
import argparse

def train(lr, momentum, num_hidden, sizes, activation, loss, opt, batch_size, anneal, save_dir, expt_dir, train_file, test_file):
    print("Training started...")
    print("lr:", lr)
    print("momentum:", momentum)
    print("num_hidden:", num_hidden)
    print("sizes:", sizes)
    print("activation:", activation)
    print("loss:", loss)
    print("opt:", opt)
    print("batch_size:", batch_size)
    print("anneal:", anneal)
    print("save_dir:", save_dir)
    print("expt_dir:", expt_dir)
    print("train_file:", train_file)
    print("test_file:", test_file)
    print("Training completed.")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Training script with command-line arguments')
    parser.add_argument('--lr', type=float, default=0.01, help='Learning rate')
    parser.add_argument('--momentum', type=float, default=0.5, help='Momentum')
    parser.add_argument('--num_hidden', type=int, default=3, help='Number of hidden layers')
    parser.add_argument('--sizes', type=str, default='100,100,100', help='Sizes of hidden layers')
    parser.add_argument('--activation', choices=['sigmoid', 'relu'], default='sigmoid', help='Activation function')
    parser.add_argument('--loss', choices=['sq', 'ce'], default='sq', help='Loss function')
    parser.add_argument('--opt', choices=['adam', 'sgd'], default='adam', help='Optimizer')
    parser.add_argument('--batch_size', type=int, default=20, help='Batch size')
    parser.add_argument('--anneal', type=bool, default=True, help='Annealing')
    parser.add_argument('--save_dir', type=str, default='pa1/', help='Save directory')
    parser.add_argument('--expt_dir', type=str, default='pa1/exp1/', help='Experiment directory')
    parser.add_argument('--train', type=str, default='train.csv', help='Training data file')
    parser.add_argument('--test', type=str, default='test.csv', help='Testing data file')

    args = parser.parse_args()
    train(args.lr, args.momentum, args.num_hidden, args.sizes, args.activation, args.loss, args.opt,
          args.batch_size, args.anneal, args.save_dir, args.expt_dir, args.train, args.test)
